pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                // Check out the source code from your version control system (e.g., Git)
                git branch: 'main', url: 'https://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@github.com/oalamad/dateTime.git'
            }
        }

        stage('Build') {
            steps {
                // Use Maven to build the Spring Boot application
                sh 'mvn clean install' // You can replace 'package' with your desired Maven goals
            }
        }

        stage('Archive Artifacts') {
            steps {
                // Archive the JAR or WAR file generated by Maven
                archiveArtifacts artifacts: '**/target/*.jar', allowEmptyArchive: true
            }
        }
    }

    post {
        success {
            // Add post-build actions here (e.g., deployment) test
            sh 'echo "build succeeded"'
        }
    }
}
